### ISSUE TITLE
Travis/S3/Cloudfront blog doesn't consider AWS Default Region completely

### ISSUE THREAD

**Issue by alanwhite** [rlucioni/blog#33]
Hi Renzo, great blog post, straight to the point. One small omission, you set the environment variable for AWS_DEAFULT_REGION but then don't mention it in the deploy section of the .travis.yml, need to set region: $AWS_DEFAULT_REGION. I guess I only discovered this as I don't use the US region!

**Comment by rlucioni** [comment]
Hey @alanwhite, thanks for opening an issue! I didn't see this earlier because of a problem with my GitHub notification preferences.

As noted in the post, I mention `AWS_DEAFULT_REGION` only because it's [required](http://docs.aws.amazon.com/general/latest/gr/rande.html#cf_region) to submit requests to CloudFront programmatically. The environment variable is internal to [aws-cli](https://github.com/aws/aws-cli#other-configurable-variables) and shouldn't need to appear in the deploy section of your `.travis.yml`. I'd only expect to see a [`region`](https://docs.travis-ci.com/user/deployment/s3/#S3-bucket-regions) key in your `.travis.yml` if you're deploying to an S3 bucket in a region other than `us-east-1`, the default.

**Comment by rlucioni** [comment]
`region` and other optional keys are covered by Travis' own S3 deployment [docs](https://docs.travis-ci.com/user/deployment/s3) which I link to. In light of that, I'm closing this as wontfix.

**Comment by rlucioni** [comment]
@alanwhite all that said: if this information would have been valuable to you, I'd be happy to review a PR adding a note about it to the post.

**Comment by alanwhite** [comment]
Hi @rlucioni, thanks for the feedback. Yeah was just in case you wanted to update. I wondered at first when I used your example why it was failing and it's because that variable wasn't reflected in the actual script. You're right it's documented everywhere so didn't take me long to figure it out. Not everybody uses the US :)

**Comment by alanwhite** [comment]
But yes, I'll contribute happily, will submit a PR and do it properly!

**Comment by rlucioni** [comment]
@alanwhite out of curiosity, have you verified that CloudFront invalidation works as expected when you specify an `AWS_DEFAULT_REGION` other than `us-east-1`? AWS docs suggest that shouldn't work. You may need to specify your non-default region separately from `AWS_DEFAULT_REGION`.

**Comment by alanwhite** [comment]
That's curious. It certainly does, I've got it set up with an S3 bucket in Ireland as the source and a custom domain name and ssl termination, all seems to work well.

**Comment by rlucioni** [comment]
@alanwhite huh, that's surprising. Maybe their docs are out of date. The AWS console shows the invalidations being triggered when Travis completes deployment?

**Comment by alanwhite** [comment]
My recent experience of AWS documentation is it's pretty but inaccurate. E.g. The API gateway lambda node.js examples return malformed responses!

**Comment by rlucioni** [comment]
I see. Good to know.
